version: '3'

services:
    web:
        build:
            context: .
        depends_on:
            - db
        ports:
            - '3000:3000'
        env_file:
            - .env
        volumes:
            - .:/var/app
    db:
        image: postgres:13.4-alpine
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
            - '5432:5432'
        volumes:
            - postgres13:/var/lib/postgresql/data
volumes:
    postgres13:
